emberjs/ember-test-waiters

addon/noop-test-waiter.ts
addon/types/index.ts
addon/waiter-manager.ts
tests/unit/waiter-manager-test.ts

The types in `waiter-manager.ts` were a little loose. This PR tightens them up a bit.

Refining types for waiter-manager

---

.github/workflows/nodejs.yml

As indicated in the description, this PR refines when the CI Build action runs. 
Borrowed from https://github.com/ember-template-lint/ember-template-lint/blob/7658c3399c5fab17eac1fabdd9d3e24be208be84/.github/workflows/ci.yml#L4-L10

Refining when CI Build runs

---

addon/noop-test-waiter.ts
addon/test-waiter.ts
addon/types/index.ts
tests/unit/test-waiter-test.ts

There are certain instances where we want to force reset all waiter items in order to ensure that waiters are not incorrectly blocking settledness in tests. This PR adds the `reset` method to the `TestWaiter` class to allow for resetting.

Add public API for clearing waiter items

---

addon/test-waiter.ts
tests/unit/test-waiter-test.ts

Currently in the `test-waiter` module, we use a zero-based counter for the default tokens. This presents a problem for consumers when checking for the existence of a valid token:
```js
let token = waiter.beginAsync();
// ...
if (token) {
waiter.endAsync(token);
}
```
This PR changes tokens to be one-based, so that the truthy evaluation will always pass, and consumers won't have to know that the first token is magically different than the rest.

Fixes default tokens to be truthy

---

.github/workflows/ci-build.yml
package.json

This PR also removes the redundant .travis.yml.

Dropping support for node 8

---

addon/wait-for-promise.ts
addon/waiter-manager.ts
tests/unit/wait-for-promise-test.ts

Related so #129
All 5 of the type errors introduced by ember-test-waiters 2.0.0 are resolved by this PR.
https://github.com/NullVoxPopuli/emberclear/pull/558

Fix Type Errors

---

README.md

This PR adds a best practices section to the README, which details recommended best practices for how to use test waiters.
[README](https://github.com/emberjs/ember-test-waiters/blob/readme-best-practices/README.md#best-practices)

Adding best practices section to readme

---

README.md
addon/build-waiter.ts
addon/index.ts
addon/wait-for-promise.ts
tests/unit/build-waiter-test.ts
tests/unit/wait-for-promise-test.ts
tests/unit/waiter-manager-noop-test.ts
tests/unit/waiter-manager-test.ts

This PR adds some constrains around the naming of test waiters. Specifically, it adds a pattern (`namespace:descriptor`) for test waiters in order to help identify them. Currently this is implemented as a warning, to avoid a breaking change.
[README](https://github.com/emberjs/ember-test-waiters/blob/waiter-label-naming/README.md) changes.

Adding constraints around naming test waiters

---

.eslintrc.js
force-highlander-addon.js
node-tests/force-highlander-addon-test.js
package.json
yarn.lock

Removes the use of a custom recursive search for discovering all addons in favor of using `ember-cli-version-checker`.

Switch to using `ember-cli-version-checker` for gathering addons

---

README.md
addon/ember-test-waiters/index.ts
addon/ember-test-waiters/types/index.ts
addon/ember-test-waiters/wait-for-promise.ts
addon/ember-test-waiters/wait-for.ts
tests/unit/wait-for-test.ts

Extracted from #81 
A couple of notes:
* I have not address https://github.com/emberjs/ember-test-waiters/pull/81#discussion_r353930902 because I'm still a typescript noob and a jsdoc noob (so noob squared here)
* I had to do some interesting acrobatics to keep the `waitForPromise` tests reasonably DRY -- I'm definitely open to other ideas if anyone has any

Extend waitForPromise to work in function form

---

README.md

In editing the README, I was battling the VSCode markdown plugin's auto-toc functionality, which also revealed a missing section, and what I think is some incorrect indentation in the toc caused by incorrect heading levels. So fi the headings, add some comments to ignore some headings we don't want in the toc, and (auto-)update the toc.

chore(docs) update README table of contents

---

RELEASE.md
package.json
yarn.lock

* Update release-it-lerna-changelog to latest
* Add `launchEditor` configuration
* Remove custom `git.changelog` script (handled by lerna-changelog now)
* Add `github.tokenRef` to use a single token
* Update `RELEASE.md`

Update automated release setup.

---

node-tests/force-highlander-addon-test.js
package.json
yarn.lock

- Update to latest `semver`
- Add test confirming future version prerelease are accounted for.

Ensure prereleases are used when present.

---

force-highlander-addon.js
index.js
node-tests/force-highlander-addon-test.js
package.json

The highlander logic in `@ember/test-waiters` is incompatible w/ `ember-engines`; this PR updates the logic to be compatible, while still maintaining the current highlander logic (latest version wins).
The rough failing scenario prior to these changes is as follows:
- When serving an engine, the engine acts as the project and the engine also is added as a dependency to the project by `ember-cli`. This basically means that if `@ember/test-waiters` is a dependency of the project, you'll get **two** instances of `@ember/test-waiters`.
- `ember-engines` has logic to decide whether an addon should be included in the actual engine being built (not the project); it does this based on a few things, but one of them being whether `@ember/test-waiters` is a dependency of the host. (Note: this logic …

Update highlander logic to be compatible with `ember-engines`

---

addon/@ember/test-waiters/build-waiter.ts
addon/@ember/test-waiters/waiter-manager.ts
package.json
tests/test-helper.js
tests/unit/build-waiter-test.ts
tests/unit/wait-for-test.ts
yarn.lock

- Avoid usage of `Set.prototype.values` for IE11 compatiblity.
- [tests] Ensure a global `Promise` is present (for transpiled async/await)
- [tests] Remove syntax from tests that is unsupported in IE11
- [tests] Use fork of ember-concurrency-decorators to fix IE11 compat.

Fix IE11 compatiblity

---

force-highlander-addon.js
index.js
node-tests/force-highlander-addon-test.js

This updates the `cacheKeyForTree` override to account for both addon names (ie, `@ember/test-waiters` and `ember-test-waiters`).
The reason for this is that Embroider doesn't currently take into account the addon's name when dealing with cache keys internally & as a result, it gets confused that (seemingly) two different addons have the same cache key. This will eventually be fixed in Embroider, but in the short-term we're implementing this here to account for this issue.
The end result is that we get a different stable cache key, one for `@ember/test-waiters` and another for `ember-test-waiters`.

update `cacheKeyForTree` override to account for both addon names

---

addon/@ember/test-waiters/build-waiter.ts
tests/unit/build-waiter-test.ts

The logic for choosing between the Map and WeakMap for completed operation tracking wasn't right, and the result was that everything was being added to the Map, leaking every token. For waitForPromise() the token is the promise itself, meaning the resolved values were also leaking, which can easily add up to a memory leak of epic proportions.

Fix potentially massive memory leak

---

addon/@ember/test-waiters/build-waiter.ts
addon/@ember/test-waiters/index.ts
addon/@ember/test-waiters/wait-for.ts
addon/@ember/test-waiters/waiter-manager.ts
config/ember-try.js
config/environment.js
ember-cli-build.js
force-highlander-addon.js
index.js
node-tests/force-highlander-addon-test.js
package.json
tests/dummy/app/router.js
tests/dummy/config/environment.js
tests/test-helper.js
tests/unit/build-waiter-test.ts
tests/unit/import-legacy-module-test.ts
tests/unit/wait-for-promise-test.ts
tests/unit/wait-for-test.ts
tests/unit/waiter-manager-noop-test.ts
tests/unit/waiter-manager-test.ts
yarn.lock

The meat of this PR is the one line change in https://github.com/emberjs/ember-test-waiters/commit/31317db4c583977b63e4f5b0b1cf0777498a8f89.
To make that work though I had to upgrade prettier, which required me to reformat a lot of the repo, and upgrade ember-cli-typescript and ember-cli-babel to make sure we would get a new enough version of `@babel/plugin-transform-typescript` to handle type-only exports.
The motivation for this change is that without marking these are type-only exports, the export statement ends up staying in the Javascript even though the corresponding type definitions got deleted. That mismatch is a SyntaxError when you're using a system that respects ES modules.

Broken type imports leak into Javascript

---

addon/ember-test-waiters/index.ts

```
DEPRECATION: When calling `deprecate` you must provide `for` in options. Missing options.for in \"ember-test-waiters-legacy-module-name\" deprecation [deprecation id: ember-source.deprecation-without-for]
DEPRECATION: When calling `deprecate` you must provide `since` in options. Missing options.since in \"ember-test-waiters-legacy-module-name\" deprecation [deprecation id: ember-source.deprecation-without-since]
```
This adds the required `for` and `since` options when creating the deprecation warning.

Fix warnings when the legacy module deprecation is triggered

---

addon/ember-test-waiters/index.ts
types/custom-ember-debug.d.ts

Fixes type mismatch introduced in #272.

Fixes TS issue with mismatched type for deprecate

---

.github/workflows/ci-build.yml

no longer fail fast on try-scenarios, as doing so makes it tedious to see what part of the build matrix passed and what part failed

no longer fail fast on try-scenarios

---

.npmignore

Our `.npmignore` was out of date, resulting in a number of extraneous files being published. This PR fixes that.
[fixes #291]

Updating .npmignore to remove unneeded files from publish

---

.github/workflows/ci-build.yml
addon/@ember/test-waiters/wait-for-promise.ts
config/ember-try.js
package.json
tests/unit/wait-for-test.ts
yarn.lock

This fixes the canary try-scenario... let's see how the other scenarios appreciate it...

Fix canary

---

tests/unit/wait-for-test.ts

1) treat `continue()` not as an idempotent function, but rather as a once time resource. This helps detect failures, specifically ones where we are cooperating with another co-routine. In-practice, this means `continue()` will throw if invoked twice for the same continuation
2) `continue()` now returns a promise, which tests now await rather than Promise.resolve. This enables the generator itself to dictate when the the active continuation has come to an end.
—
After debugging, it really just came down to the fact that `await Promise.resolve()` and the `yieldable` used in this test implicitly depended on something they really should not have. Ember 3.16 and 3.20 had slightly different glimmer dirty-tracking behaviors, which resulted in the mixture of native promises and ember auto-run …

Fix Failing Tests resulting from ember-concurrency v2 bump

---

addon/@ember/test-waiters/build-waiter.ts

This code seems to be optimized by babel, uglify or similar into something like this:
```js
define("@ember/test-waiters/build-waiter", [ "exports", "@ember/debug", "@ember/test-waiters/token", "@ember/test-waiters/waiter-manager" ], (function(e, t, r, n) {
"use strict";
Object.defineProperty(e, "__esModule", {
value: !0
});
e._resetWaiterNames = function() {
a = new Set;
};
e.default = function(e) {
0;
return new l(e);
return new s(e);
};
function i(e, t, r) {
t in e ? Object.defineProperty(e, t, {
value: r,
enumerable: !0,
configurable: !0,
writable: !0
}) : e[t] = r;
return e;
}
let a;
function o() {
return new r.default;
}
class s {
constructor(e, t) {
i(this, "isRegistered", !1);
i(this, "items", new Map);
i(this, "completedOperationsForTokens", new WeakMap);
i(this, …
```

Avoid unreachable code after return warning

---

package.json

As indicated by the package, this should be a dependency, not a devDep.

Moving ember-cli-typescript to dependencies

---

addon/@ember/test-waiters/waiter-manager.ts

Currently, we rely heavily on the highlander logic to ensure that we can **only** ever have one version of `@ember/test-waiters` in the build outpu. The reason for this is so that when someone calls `hasPendingWaiters()` we can reliably ensure that _**ALL**_ waiters that have been registered (regardless of version mismatches and whatnot) are found.
Unfortunately, we cannot actually rely on the highlander logic to guarantee this "waiter map" uniqueness in Embroider builds (because the highlander logic is broken by the isolated nature of Embroiders compatibility layer).
This change migrates from a strict reliance on the highlander logic to guarantee the module scoped variable is shared globally to a mechanism of sharing the state on `globalThis` (with fallbacks for various other scenarios). …

Ensure waiters are discovered even if multiple versions exist

---

tests/dummy/config/targets.js

Extracted from: https://github.com/emberjs/ember-test-waiters/pull/455
Goal: Get C.I. green with the fewest changes possible.
(all the other changes in my PRs do still need to be merged tho -- just want to make sure changes are targeted -- bigger PRs are split out and rebased as things get merged / discovered)

Remove IE11 from targets as the browser is not supported anymore

---

addon/@ember/test-waiters/wait-for.ts
tests/unit/wait-for-test.ts

Use type arguments & inference to ensure that `waitFor()` in function form returns the same type that it was passed. This prevents it from getting in the way of passing functions as as typed arguments. For example, `ember-concurrency`'s `task()` function expects an async arrow function as its argument, so `task(async () => null)` works, but without this change, `task(waitFor(() => null))` does not because `waitFor(() => null)` is just `Function`.

Improve waitFor() types

---

package-lock.json
package.json

Context, Plan, etc: https://gist.github.com/NullVoxPopuli/eafc7dad6547de5e730098498b829e1f
This PR is mostly a no-op be eai2 is required to consume v2 addons.
This will be a breaking change.
I breaking change is a bit of a shame, but this is only a semver communication -- the APIs for modern apps should still be the same, and we can recommend overrides configs for folks to ensure that they only have one copy of `@ember/test-waiters` in their projects.
Moving to a monorepo will allow a good variety of test apps to showcase this.

Require ember-auto-import@v2

---

addon/package.json
pnpm-lock.yaml

We want to use ember-source's built in types for internal type checking, and we can't do that with TS < v4.9
TS v4.9 was released November of 2022

Drop support for Typescript < 4.9

---

addon/addon/waiter-manager.ts

tl;dr: I didn't want to figure out how to type `global` as a global, and since only node has `global`... we don't need to care about its existence (since any js runtime that has `global` also has `globalThis` -- which we do support)
for node / fastboot, `globalThis` was introduced in Node 12, which we already don't support as it's far beyond LTS support period. Prior to Node 12, this library will no longer work in fastboot mode (so you'd have to use `v3.x` of test-waiters).

Drop support for the 'global' global. Every supported environment has `globalThis`

---

addon/addon/waiter-manager.ts

The new waiter system was introduced in 2020: https://rfcs.emberjs.com/id/0581-new-test-waiters

Drop support legacy waiter system

---

pnpm-lock.yaml
test-apps/base-tests/package.json
test-apps/ember-concurrency-v2/package.json
test-apps/ember-fetch-v8/package.json

ember-data isn't used in the tests for this package, so we don't need to have it installed.

Remove ember-data from dev-dependencies

---

addon/package.json
test-apps/base-tests/package.json
test-apps/ember-concurrency-v2/package.json
test-apps/ember-fetch-v8/package.json

`npx ember-apply@latest volta` applies a local-only affects no-one except volta-users (as benefit).

Setup local volta configs

---

addon/src/index.ts
addon/src/wait-for-fetch.ts
test-apps/base-tests/package.json
test-apps/base-tests/tests/unit/wait-for-fetch-test.ts

- https://github.com/emberjs/rfcs/pull/1065

Implement functionally for "deprecate fetch" RFC
